ST-37-uniqueDB
dnguyen000/ICS-499 pull request #15
Opened 2022-02-15 23:30 UTC by dnguyen000

Changes:

- Update .gitignore to ignore metadata directory
- added mockito to pom.xml (will be used to unit test HTTP requests and handle expected returned data)
- Added Services and ServiceImp packages for Flashcard and Element classes. This follows the example Zak provided in class. There's definitely room to improve here, possibly making just one abstract Service class with the method isValid and has an Object parameter

2022-02-16 00:05 UTC, atvick21 approved these changes

2022-02-16 00:14 UTC, f947 approved these changes

2022-02-16 02:35 UTC, wale0 approved these changes

2022-02-16 05:07 UTC, calebTree commented
On this one, the easiest way to move through the conflicts would be with `git rebase -r main`.

2022-02-16 05:13 UTC, calebTree requested changes
Just waiting for conflicts to be resolved.

2022-02-18 05:19 UTC, calebTree approved these changes
I noticed a design decision to consolidate the service interface into one class and package. That looks like a good design.

2022-02-18 05:20 UTC, merged